site_name: CPSS Flight Operating System
nav:
  - Home: index.md
  - Software Guidelines:
      - Code Style: software_guidelines/code-style.md
      - Git Workflow: software_guidelines/git-workflow.md
      - Using GitHub: software_guidelines/using-github.md
  - Language Specification: language-spec.md
theme: readthedocs
